import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

/**
 * File storage on the local disk (a mounted volume in Docker). Keys are generated by us,
 * never taken from user input. An S3/MinIO backend can implement the same interface later.
 */
export interface Storage {
  put(key: string, data: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

export function createLocalStorage(root: string): Storage {
  const base = resolve(root);
  const path = (key: string) => {
    const p = resolve(join(base, key));
    if (!p.startsWith(base + "/")) throw new Error("Invalid storage key");
    return p;
  };
  return {
    async put(key, data) {
      const p = path(key);
      await mkdir(dirname(p), { recursive: true });
      await writeFile(p, data);
    },
    get: (key) => readFile(path(key)),
    async remove(key) {
      await rm(path(key), { force: true });
    },
  };
}
