import { CreateBucketCommand, DeleteObjectCommand, GetObjectCommand, HeadBucketCommand, PutObjectCommand, S3Client, type S3ClientConfig } from "@aws-sdk/client-s3";
import { randomBytes } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

/**
 * File storage for uploads (documents, project files, the logo). Keys are generated by us, never
 * taken from user input. Two backends: the local disk (a mounted volume in Docker) or any
 * S3-compatible service (AWS S3, MinIO, Ceph, SeaweedFS, Garage, Cloudflare R2…).
 * Work AI task folders and IDE homes are working directories and always stay on local disk.
 */
export interface Storage {
  put(key: string, data: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
  /** Where files go, for logs and the admin overview (no secrets). */
  describe(): string;
  /** Proves the backend can write, read and delete; throws a readable error otherwise. */
  check(): Promise<void>;
}

/** Thrown by get() for a key that doesn't exist, whatever the backend. */
export class StorageNotFound extends Error {
  readonly code = "ENOENT";
  constructor(key: string) {
    super(`No stored file at ${key}`);
  }
}

function validKey(key: string) {
  if (!key || key.startsWith("/") || key.split("/").some((p) => p === "" || p === "." || p === "..")) throw new Error("Invalid storage key");
  return key;
}

async function roundTrip(s: Pick<Storage, "put" | "get" | "remove">) {
  const key = `.aatmiq-check/${randomBytes(8).toString("hex")}`;
  const data = Buffer.from("aatmiq storage check");
  await s.put(key, data);
  const back = await s.get(key);
  await s.remove(key);
  if (!back.equals(data)) throw new Error("a file read back differently than it was written");
}

export function createLocalStorage(root: string): Storage {
  const base = resolve(root);
  const path = (key: string) => {
    const p = resolve(join(base, validKey(key)));
    if (!p.startsWith(base + "/")) throw new Error("Invalid storage key");
    return p;
  };
  const s: Storage = {
    async put(key, data) {
      const p = path(key);
      await mkdir(dirname(p), { recursive: true });
      await writeFile(p, data);
    },
    async get(key) {
      try {
        return await readFile(path(key));
      } catch (e) {
        if ((e as NodeJS.ErrnoException).code === "ENOENT") throw new StorageNotFound(key);
        throw e;
      }
    },
    async remove(key) {
      await rm(path(key), { force: true });
    },
    describe: () => `local disk (${base})`,
    async check() {
      try {
        await roundTrip(s);
      } catch (e) {
        throw new Error(`File storage at ${base} doesn't work: ${(e as Error).message}`);
      }
    },
  };
  return s;
}

export interface S3Config {
  bucket: string;
  /** Empty for AWS S3; the service's URL otherwise (http://minio:9000, https://<account>.r2.cloudflarestorage.com…). */
  endpoint: string | null;
  region: string;
  /** Empty: the AWS default chain (IAM role, AWS_* variables, ~/.aws). */
  accessKeyId: string | null;
  secretAccessKey: string | null;
  /** bucket in the path (MinIO and most self-hosted services) rather than in the hostname. */
  forcePathStyle: boolean;
  /** Optional folder inside the bucket, e.g. "aatmiq/". */
  prefix: string;
  /** Server-side encryption to ask for on upload ("AES256" or "aws:kms"); empty for none. */
  sse: "AES256" | "aws:kms" | null;
  /** Create the bucket at start when it doesn't exist (handy with the bundled MinIO). */
  createBucket?: boolean;
}

export function s3Client(c: S3Config): S3Client {
  const opts: S3ClientConfig = {
    region: c.region,
    forcePathStyle: c.forcePathStyle,
    ...(c.endpoint ? { endpoint: c.endpoint } : {}),
    ...(c.accessKeyId && c.secretAccessKey ? { credentials: { accessKeyId: c.accessKeyId, secretAccessKey: c.secretAccessKey } } : {}),
    // Don't add checksums some S3-compatible services reject; still verify them when present.
    requestChecksumCalculation: "WHEN_REQUIRED",
    responseChecksumValidation: "WHEN_REQUIRED",
  };
  return new S3Client(opts);
}

/** "aatmiq" → "aatmiq/"; empty stays empty. */
export const s3Prefix = (prefix: string) => (prefix ? prefix.replace(/^\/+/, "").replace(/\/*$/, "/") : "");

export function createS3Storage(c: S3Config, client?: S3Client): Storage {
  const s3 = client ?? s3Client(c);
  const prefix = s3Prefix(c.prefix);
  const Key = (key: string) => prefix + validKey(key);
  const where = `S3 bucket "${c.bucket}"${prefix ? ` (folder ${prefix})` : ""}${c.endpoint ? ` at ${c.endpoint}` : ` in ${c.region}`}`;
  const s: Storage = {
    async put(key, data) {
      await s3.send(
        new PutObjectCommand({ Bucket: c.bucket, Key: Key(key), Body: data, ContentLength: data.length, ...(c.sse ? { ServerSideEncryption: c.sse } : {}) }),
      );
    },
    async get(key) {
      try {
        const r = await s3.send(new GetObjectCommand({ Bucket: c.bucket, Key: Key(key) }));
        return Buffer.from(await r.Body!.transformToByteArray());
      } catch (e) {
        const err = e as { name?: string; $metadata?: { httpStatusCode?: number } };
        if (err.name === "NoSuchKey" || err.$metadata?.httpStatusCode === 404) throw new StorageNotFound(key);
        throw e;
      }
    },
    async remove(key) {
      // Deleting a key that isn't there succeeds, as on disk with force.
      await s3.send(new DeleteObjectCommand({ Bucket: c.bucket, Key: Key(key) }));
    },
    describe: () => where,
    async check() {
      try {
        await s3.send(new HeadBucketCommand({ Bucket: c.bucket }));
      } catch (e) {
        const err = e as { name?: string; message?: string; $metadata?: { httpStatusCode?: number } };
        const status = err.$metadata?.httpStatusCode;
        const missing = status === 404 || err.name === "NotFound" || err.name === "NoSuchBucket";
        if (missing && c.createBucket) {
          await s3.send(new CreateBucketCommand({ Bucket: c.bucket })).catch((ce: Error) => {
            throw new Error(`${where} doesn't exist and couldn't be created: ${ce.message}`);
          });
          return roundTrip(s);
        }
        const why =
          missing
            ? "the bucket doesn't exist. Create it first (or set S3_CREATE_BUCKET=true)"
            : status === 403 || status === 401
              ? "access was refused. Check S3_ACCESS_KEY_ID / S3_SECRET_ACCESS_KEY and the bucket policy"
              : err.message || err.name || "no answer";
        throw new Error(`${where} isn't usable: ${why}.`);
      }
      try {
        await roundTrip(s);
      } catch (e) {
        throw new Error(`${where} isn't usable: writing, reading or deleting a test file failed (${(e as Error).message}). The access key needs s3:PutObject, s3:GetObject and s3:DeleteObject.`);
      }
    },
  };
  return s;
}

export function createStorage(cfg: { storageDir: string; s3?: S3Config | null }): Storage {
  return cfg.s3 ? createS3Storage(cfg.s3) : createLocalStorage(cfg.storageDir);
}
